# Local 테스트용 프로필 (DB 없이 테스트)
# 사용법: ./gradlew :server:bootRun --args='--spring.profiles.active=local'

spring:
  application:
    name: deeplink-server-local
  
  # H2 in-memory 데이터베이스 (설치 불필요)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (http://localhost:8080/h2-console)
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # 시작할 때 테이블 생성, 종료할 때 삭제
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Redis 비활성화 (없어도 동작)
  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

server:
  port: 8080

deeplink:
  # 테스트용 설정
  matching-window-ms: 86400000  # 24시간
  link-expiry-ms: 2592000000    # 30일
  base-url: http://localhost:8080

logging:
  level:
    com.deeplink.server: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

