name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-library:
    name: Build Library
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build Library
      run: ./gradlew :library:build --no-daemon
    
    - name: Run Common Tests
      run: ./gradlew :library:allTests --no-daemon
      continue-on-error: true

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build Server
      run: ./gradlew :server:build --no-daemon

  build-android-sample:
    name: Build Android Sample
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build Android Sample
      run: ./gradlew :sample-android:assembleDebug --no-daemon
